---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-cache
  failurePolicy: Fail
  name: vcache.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - caches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-cronhotbackup
  failurePolicy: Ignore
  name: vcronhotbackup.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cronhotbackups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-hazelcast
  failurePolicy: Ignore
  name: vhazelcast.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hazelcasts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-hazelcastendpoint
  failurePolicy: Fail
  name: vhazelcastendpoint.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hazelcastendpoints
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-hotbackup
  failurePolicy: Ignore
  name: vhotbackup.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - hotbackups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-jetjob
  failurePolicy: Fail
  name: vjetjob.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jetjobs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-jetjobsnapshot
  failurePolicy: Fail
  name: vjetjobsnapshot.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jetjobsnapshots
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-managementcenter
  failurePolicy: Ignore
  name: vmanagementcenter.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - managementcenters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-map
  failurePolicy: Ignore
  name: vmap.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - maps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-multimap
  failurePolicy: Ignore
  name: vmultimap.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - multimaps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-queue
  failurePolicy: Ignore
  name: vqueue.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - queues
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-replicatedmap
  failurePolicy: Fail
  name: vreplicatedmap.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - replicatedmaps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-topic
  failurePolicy: Ignore
  name: vtopic.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - topics
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-usercodenamespace
  failurePolicy: Fail
  name: vusercodenamespace.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - usercodenamespaces
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-wanreplication
  failurePolicy: Ignore
  name: vwanreplication.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - wanreplications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hazelcast-com-v1alpha1-wansync
  failurePolicy: Fail
  name: vwansync.kb.io
  rules:
  - apiGroups:
    - hazelcast.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - wansyncs
  sideEffects: None
