apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  clusterSize: 3
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  version: '5.1'
  licenseKeySecret: hazelcast-license-key
  persistence:
    baseDir: "/data/persistence/"
    clusterDataRecoveryPolicy: "FullRecoveryOnly"
    pvc:
      accessModes: ["ReadWriteOnce"]
      requestStorage: 8Gi
      storageClassName: "standard"
  backup:
    agentRepository: hasancelik/platform-operator-agent
    agentVersion: 0.1.5
    bucketSecret: br-secret
