name: Cleanup namespaces
on:
  workflow_call:
    inputs:
      cluster_type:
        type: string
        required: true
      cluster_name:
        type: string
        required: true
      namespaces:
        description: 'Coma-separated namespaces to be cleaned up'
        type: string
        required: true
      gke_zone:
        type: string
        required: false
        default: 'us-east1-b'
      gcp_project_id:
        type: string
        required: false
        default: 'hazelcast-33'
      aws_region:
        type: string
        required: false
        default: 'us-east-1'
      azure_resource_group:
        type: string
        required: false
        default: operator-test
    secrets:
      GKE_SA_KEY:
        required: true
jobs:
  cleanup-namespaces:
    name: Cleanup namespaces
    env:
      CLUSTER_TYPE: ${{ inputs.cluster_type }}
      CLUSTER_NAME: ${{ inputs.cluster_name }}
      NAMESPACES: ${{ inputs.namespaces }}
      GKE_ZONE: ${{ inputs.gke_zone }}
      GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
      AWS_REGION: ${{ inputs.aws_region }}
      AZURE_RESOURCE_GROUP: ${{ inputs.azure_resource_group }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: "google-github-actions/auth@v1.1.1"
        if: ${{ contains(inputs.cluster_type, 'gke') }}
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Connect to the GKE cluster
        uses: 'google-github-actions/get-gke-credentials@v1'
        if: ${{ contains(inputs.cluster_type, 'gke') }}
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          location: ${{ env.GKE_ZONE }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.1.0
        if: ${{ contains(inputs.cluster_type, 'eks') }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        if: ${{ contains(inputs.cluster_type, 'eks') }}
        run: |-
          aws eks update-kubeconfig --name "${{ env.CLUSTER_NAME }}"

      - name: Azure login
        uses: azure/login@v1
        if: ${{ contains(inputs.cluster_type, 'aks') }}
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update kubeconfig
        if: ${{ contains(inputs.cluster_type, 'aks') }}
        run: |-
          az aks get-credentials --resource-group "${AZURE_RESOURCE_GROUP}" --name "${{ env.CLUSTER_NAME }}"

      - name: Cleaning up Namespaces
        timeout-minutes: 10
        run: |-
          source .github/scripts/utils.sh
          for ns in $(echo ${NAMESPACES} | sed "s/,/ /g")
          do
            echo "running the script to cleanup '$ns'"
            cleanup_namespace "$ns"
          done
