name: Delete K8S Cluster
on:
  workflow_dispatch:
    inputs:
      provider:
        description: 'EKS, GKE or AKS'
        required: true
      cluster-name:
        required: true
        description: 'K8s cluster to delete'

env:
  CLUSTER_NAME: ${{ github.event.inputs.cluster-name }}
  AWS_REGION: us-east-1

jobs:
  delete-azure:
    if: github.event.inputs.provider == 'AKS'
    name: Delete the given K8s cluster
    runs-on: ubuntu-latest
    env:
      AZURE_RESOURCE_GROUP: hazelcast-platform-operator
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            AZURE_CREDENTIALS,CN/AZURE_CREDENTIALS

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Delete AKS cluster
        uses: azure/CLI@v1
        with:
          azcliversion: 2.31.0
          inlineScript: |
            az aks delete --name "${CLUSTER_NAME}" --resource-group "${AZURE_RESOURCE_GROUP}" -y

  delete-aws:
    if: github.event.inputs.provider == 'EKS'
    name: Delete the given K8s cluster
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install eksctl
        run: |-
          curl --silent --location \
            "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
            | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Delete EKS cluster
        run: |-
          eksctl delete nodegroup --cluster "${CLUSTER_NAME}" --name node-group-1
          eksctl delete cluster "${CLUSTER_NAME}" --wait

  delete-gcp:
    if: github.event.inputs.provider == 'GKE'
    name: Delete the given K8s cluster
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: hazelcast-33
      GKE_ZONE: us-east1-b
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            GKE_SA_KEY,CN/GKE_SA_KEY

      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v1.1.1'
        with:
          credentials_json: ${{ env.GKE_SA_KEY }}

      - name: Delete GKE cluster
        run: |-
          gcloud container clusters delete ${{ env.CLUSTER_NAME }} --zone ${{ env.GKE_ZONE }} --quiet
