name: High Availability tests on GKE
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 9 */3 * *"

env:
  GCP_PROJECT_ID: hazelcast-33
  CLOUD_KEY_SECRET_NAME: cloud-key-secret
  CHAOS_MESH_NAMESPACE: chaos-mesh

jobs:
  create-gke-cluster:
    name: Create GKE Cluster
    runs-on: ubuntu-latest
    outputs:
      CLUSTER_NAME: ${{ steps.set-cluster-name.outputs.CLUSTER_NAME }}
      GKE_REGION: ${{ steps.set-cluster-name.outputs.GKE_REGION }}
    env:
      GCP_NETWORK: operator-test-network
      GKE_REGION: europe-west1
    steps:
      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v1.0.0'
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Create GKE cluster
        id: set-cluster-name
        run: |-
          CLUSTER_NAME="operator-ha-test-${GITHUB_SHA::8}-${{ github.run_number }}"
          echo "CLUSTER_NAME=${CLUSTER_NAME}" >> $GITHUB_OUTPUT
          echo "GKE_REGION=${GKE_REGION}" >> $GITHUB_OUTPUT
          gcloud container clusters create ${CLUSTER_NAME} \
            --region=${{ env.GKE_REGION }} \
            --project=${{ env.GCP_PROJECT_ID }} \
            --network=${{ env.GCP_NETWORK }} \
            --machine-type=n1-standard-2 \
            --num-nodes=2 \
            --node-locations "${GKE_REGION}-c","${GKE_REGION}-d"
          sleep 30

  grafana-setup:
    needs: [ create-gke-cluster ]
    uses: ./.github/workflows/grafana-agent.yaml
    secrets: inherit
    with:
      cluster_name: ${{ needs.create-gke-cluster.outputs.CLUSTER_NAME }}
      cluster_type: gke-high-availability
      gke_zone: ${{ needs.create-gke-cluster.outputs.GKE_REGION }}
      gh_run_id: ${{ github.run_id }}
      gh_run_number: ${{ github.run_number }}
      gh_sha: ${{ github.sha }}
      namespaces: "test-operator-high-availability"

  get-image:
    name: Get Image
    runs-on: ubuntu-latest
    outputs:
      IMG: ${{ steps.build-img.outputs.IMG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push image to ttl.sh
        id: build-img
        run: |
          if [[ "${{github.event_name}}" == "workflow_dispatch" || "${{github.event_name}}" == "pull_request" ]]; then
            IMG=ttl.sh/$(uuidgen):2h
            make docker-build-ci IMG=$IMG VERSION=${{github.sha}}
            make docker-push IMG=$IMG
            echo "IMG=${IMG}" >> $GITHUB_OUTPUT
          else
            IMG=hazelcast/hazelcast-platform-operator:latest-snapshot
            echo "IMG=${IMG}" >> $GITHUB_OUTPUT
          fi

  gke-high-availability-tests:
    name: Run High Availability tests
    runs-on: ubuntu-latest
    needs: [ create-gke-cluster, grafana-setup, get-image ]
    env:
      IMG: ${{ needs.get-image.outputs.IMG }}
      NAMESPACE: test-operator-high-availability
      CLUSTER_NAME: ${{ needs.create-gke-cluster.outputs.CLUSTER_NAME }}
      GKE_REGION: ${{ needs.create-gke-cluster.outputs.GKE_REGION }}
      RELEASE_NAME: high-availability-${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"

      - name: Cache Golang dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Authenticate to GCP
        uses: "google-github-actions/auth@v1.0.0"
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Connect to the GKE cluster
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          location: ${{ env.GKE_REGION }}

      - name: Deploy Operator to GKE
        run: |
          kubectl create namespace ${{ env.NAMESPACE }}
          kubectl config set-context --current --namespace=$NAMESPACE
          
          DEPLOY_NAME=${RELEASE_NAME}-hazelcast-platform-operator
          make deploy IMG=$IMG NAMESPACE=$NAMESPACE RELEASE_NAME=$RELEASE_NAME PHONE_HOME_ENABLED=${{ env.PHONE_HOME_ENABLED }}
          kubectl rollout status deployment $DEPLOY_NAME

      - name: Deploy ChaosMesh to GKE
        run: |
          helm repo add chaos-mesh https://charts.chaos-mesh.org
          kubectl create ns ${CHAOS_MESH_NAMESPACE}
          helm install chaos-mesh chaos-mesh/chaos-mesh -n=${CHAOS_MESH_NAMESPACE} --version 2.5.1
          kubectl get po -n ${CHAOS_MESH_NAMESPACE}

      - name: Create secrets
        run: |
          kubectl create secret generic hazelcast-license-key \
            --namespace ${NAMESPACE} --from-literal=license-key=${{ secrets.HZ_LICENSE_KEY }}

          GKE_SA_BASE64=$(echo -E '${{ secrets.GKE_SA_KEY }}' | base64)
          kubectl create secret generic ${CLOUD_KEY_SECRET_NAME} \
            --namespace ${CHAOS_MESH_NAMESPACE} --from-literal=service_account="$GKE_SA_BASE64"

      - name: Run high Availability tests at GKE
        run: make test-high-availability NAMESPACE=$NAMESPACE RELEASE_NAME=$RELEASE_NAME REPORT_SUFFIX=01 WORKFLOW_ID=high-availability

      - name: Clean up after Tests
        if: always()
        run: |
          make clean-up-namespace NAMESPACE=${NAMESPACE}
          helm uninstall chaos-mesh -n ${CHAOS_MESH_NAMESPACE}

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report-high-availability
          path: allure-results/high-availability/

  report-generation:
    needs: [ "create-gke-cluster", "gke-high-availability-tests" ]
    if: always() && (needs.gke-high-availability-tests.result == 'success' || needs.gke-high-availability-tests.result == 'failure')
    uses: ./.github/workflows/generate-test-report.yaml
    secrets: inherit
    with:
      WORKFLOW_ID: high-availability
      CLUSTER_NAME: ${{ needs.create-gke-cluster.outputs.CLUSTER_NAME }}

  delete-cluster:
    name: Delete High Availability cluster
    runs-on: ubuntu-latest
    if: always()
    needs: [ create-gke-cluster, gke-high-availability-tests ]
    env:
      CLUSTER_NAME: ${{ needs.create-gke-cluster.outputs.CLUSTER_NAME }}
      GKE_REGION: ${{ needs.create-gke-cluster.outputs.GKE_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: "google-github-actions/auth@v1.0.0"
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Delete GKE cluster
        run: |-
          gcloud container clusters delete ${{ env.CLUSTER_NAME }} --region ${{ env.GKE_REGION }} --quiet

  slack_notify:
    name: Slack Notify
    needs: [ "gke-high-availability-tests", "delete-cluster" ]
    if: always() &&  ( needs.gke-high-availability-tests.result != 'success' || needs.delete-cluster.result != 'success')
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@a189acbf0b7ea434558662ae25a0de71df69a435
        with:
          fields: repo,commit,author,action,eventName,workflow
          status: failure
          channel: "#github-actions-log"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
